export const MOCK_USERS = [
  {
    ID: 0,
    FirstName: "Chris",
    LastName: "Koester",
    Email: "chris.k@courthousecomputersystems.com",
    CompanyID: 1,
    IsCCS: 0,
    IsActive: 1,
    IsWorking: 1,
    UserRoleID: 1,
    CurrentProjectID: 1,
    UserName: "chrisk",
    Password: "chrisk",
    AuthCode: "000"
  },
  {
    ID: 2,
    FirstName: "CJ",
    LastName: "Rowland",
    Email: "cj.r@courthousecomputersystems.com",
    CompanyID: 1,
    IsCCS: 0,
    IsActive: 1,
    IsWorking: 1,
    UserRoleID: 3,
    CurrentProjectID: 1,
    UserName: "cj",
    Password: "cj",
    AuthCode: "111"
  },
  {
    ID: 3,
    FirstName: "Heather",
    LastName: "M",
    Email: "heather.m@courthousecomputersystems.com",
    CompanyID: 1,
    IsCCS: 0,
    IsActive: 0,
    IsWorking: 1,
    UserRoleID: 2,
    CurrentProjectID: 1,
    UserName: "heatherm",
    Password: "heatherm",
    AuthCode: "222"
  },
  {
    ID: 4,
    FirstName: "Anastasia",
    LastName: "Evseeva",
    Email: "anastasiia.e@courtousecomputersystems.com",
    CompanyID: 1,
    IsCCS: 0,
    IsActive: 0,
    IsWorking: 1,
    UserRoleID: 3,
    CurrentProjectID: 1,
    UserName: "anastasiiae",
    Password: "anastasiiae",
    AuthCode: "333"
  },
  {
    ID: 8,
    FirstName: "Jacob",
    LastName: "Ferrebee",
    Email: "jacob.f@ccs-scan.com",
    CompanyID: 1,
    IsCCS: 0,
    IsActive: 0,
    IsWorking: 1,
    UserRoleID: 3,
    CurrentProjectID: 1,
    UserName: "jacobf",
    Password: "jacobf",
    AuthCode: "888"
  },
  {
    ID: 6,
    FirstName: "Yana",
    LastName: "Burdakova",
    Email: "yana.b@ccs-scan.com",
    CompanyID: 1,
    IsCCS: 0,
    IsActive: 1,
    IsWorking: 1,
    UserRoleID: 1,
    CurrentProjectID: 1,
    UserName: "yanab",
    Password: "yanab",
    AuthCode: "555"
  },
]